apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "configmap-watcher.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "configmap-watcher.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "configmap-watcher.chart" . }}
    release: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "configmap-watcher.fullname" . }}
subjects:
  - name: {{ .Values.serviceAccount.name }}
    namespace: {{ .Release.Namespace | quote }}
    kind: ServiceAccount
