name: ibm-configmap-watcher
apiVersion: v1
version: "1.0.0"
appVersion: "1.0.0"
tillerVersion: ">=2.7.0"
kubeVersion: ">=1.11.0"
description: "A helm chart for deploying the config map watcher component."
keywords:
  - configmap
  - watcher
  - kubernetes
  - ICP
  - amd64
  - s390x
  - ppc64le
  - Tools
  - Development
  - Tech
