global:
  pullSecret: ""

replicaCount: 1

imageTagPostfix: ""
image: 
  name: configmap-watcher
  repository: quay.io/open-cluster-management
  tag: 3.3.1
  pullPolicy: IfNotPresent

args:
  verbosity: 0
  cleanFreq:
  gatherFreq:
  checkConfigmapFreq:

serviceAccount:
  name: default
  create: false

securityContext:
  pod:
    runAsNonRoot: true
  container:
    privileged: false
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    runAsNonRoot: true

affinity: {}

tolerations:
  - effect: NoSchedule
    key: dedicated
    operator: Exists
  - key: CriticalAddonsOnly
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/not-ready
    operator: Exists

resources:
  limits:
    memory: "300Mi"
    cpu: "200m"
  requests:
    memory: "150Mi"
    cpu: "100m"

imagePullSecrets: []
