global:
  pullSecret: ""
  imageOverrides:
    configmap_watcher: ""
  pullPolicy: Always

replicaCount: 1

args:
  verbosity: 0
  cleanFreq:
  gatherFreq:
  checkConfigmapFreq:

serviceAccount:
  name: default
  create: false

securityContext:
  pod:
    runAsNonRoot: true
  container:
    privileged: false
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    runAsNonRoot: true

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 70
      podAffinityTerm:
        topologyKey: failure-domain.beta.kubernetes.io/zone
        labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - configmap-watcher
    - weight: 35
      podAffinityTerm:
        topologyKey: kubernetes.io/hostname
        labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - configmap-watcher


tolerations: {}

hubconfig:
  nodeSelector: null

resources:
  limits:
    memory: "800Mi"
    cpu: "800m"
  requests:
    memory: "250Mi"
    cpu: "200m"

imagePullSecrets: []
