global:
  pullSecret: ""
  imageOverrides:
    configmap_watcher: ""
  pullPolicy: IfNotPresent

replicaCount: 1

args:
  verbosity: 0
  cleanFreq:
  gatherFreq:
  checkConfigmapFreq:

serviceAccount:
  name: default
  create: false

securityContext:
  pod:
    runAsNonRoot: true
  container:
    privileged: false
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    runAsNonRoot: true

affinity: {}

tolerations: {}

resources:
  limits:
    memory: "300Mi"
    cpu: "200m"
  requests:
    memory: "150Mi"
    cpu: "100m"

imagePullSecrets: []
