org: open-cluster-management

global:
  pullSecret: ""
  imageOverrides:
    configmap_watcher: ""
  pullPolicy: Always

args:
  verbosity: 0
  cleanFreq:
  gatherFreq:
  checkConfigmapFreq:

serviceAccount:
  name: default
  create: false

securityContext:
  pod:
    runAsNonRoot: true
  container:
    privileged: false
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    runAsNonRoot: true

tolerations:
- effect: NoSchedule 
  key: node-role.kubernetes.io/infra 
  operator: Exists

hubconfig:
  nodeSelector: null
  replicaCount: 1

resources:
  limits:
    memory: "800Mi"
    cpu: "800m"
  requests:
    memory: "250Mi"
    cpu: "100m"

imagePullSecrets: []
